-- define unity type
luanet.load_assembly('Assembly-CSharp')
AssetsLoader = luanet.import_type('SpaceCitizen.AssetsLoader')
UIManager = luanet.import_type('SpaceCitizen.UIManager')
UIEventListener = luanet.import_type('UIEventListener')
NotificationCenter = luanet.import_type('SpaceCitizen.NotificationCenter')
LuaMemberMethod = luanet.import_type('SpaceCitizen.LuaMemberMethod')
GlobalLoop = luanet.import_type('SpaceCitizen.GlobalLoop')
SceneManager = luanet.import_type('SpaceCitizen.SceneManager')
Trace = luanet.import_type('SpaceCitizen.Trace')
LuaMonoBehaviour = luanet.import_type('SpaceCitizen.LuaMonoBehaviour')

luanet.load_assembly('UnityEngine')
GameObject = luanet.import_type('UnityEngine.GameObject')
Object = luanet.import_type('UnityEngine.Object')
CameraClearFlags = luanet.import_type('UnityEngine.CameraClearFlags')
Camera = luanet.import_type('UnityEngine.Camera')
Color = luanet.import_type('UnityEngine.Color')
Input = luanet.import_type('UnityEngine.Input')
Vector3 = luanet.import_type('UnityEngine.Vector3')
Application = luanet.import_type('UnityEngine.Application')
Quaternion = luanet.import_type('UnityEngine.Quaternion')
Time = luanet.import_type('UnityEngine.Time')
Mathf = luanet.import_type('UnityEngine.Mathf')
Texture2D = luanet.import_type('UnityEngine.Texture2D')
Screen = luanet.import_type('UnityEngine.Screen')
TextureFormat = luanet.import_type('UnityEngine.TextureFormat')
Rect = luanet.import_type('UnityEngine.Rect')
RenderTexture = luanet.import_type('UnityEngine.RenderTexture')
RenderTextureFormat = luanet.import_type('UnityEngine.RenderTextureFormat')